### ISSUE TITLE
Legal links to invalid URL

### ISSUE THREAD

**Issue by piantino** [open-eid/org#1]
Page:
https://github.com/open-eid/org/blob/master/CONTRIBUTING.md

Phase:
Contributors must conform to Certificate of Origin v1.1 and use the associated process (add a Signed-off-by tag to your commits), similar to what exists in Linux kernel development.

Links:
https://ltsi.linuxfoundation.org/developers/signed-process (404)
https://www.kernel.org/doc/Documentation/SubmittingPatches
(This file has moved to process/submitting-patches.rst)

**Comment by metsma** [comment]
Fixed in 78b68af7df1f6eaff62ed35e4315af7c53f924fc
